### PR TITLE
Added support to specify the network used by container

### PR DESCRIPTION
**Pull request by smurfy**
I'm using ddev and need to have the testcontainer in the same network, so with this PR you can specify the docker network it should use.

Also useful in other cases where docker compose is used.

Basically like: https://github.com/testcontainers/testcontainers-java/blob/main/core/src/main/java/org/testcontainers/containers/Container.java#L283

### CODE REVIEW

**Review by shyim — APPROVED** [review]

**Comment by smurfy** [comment]
Anything i need to fix for the piplines to pass? Looks like an unrelated issue

**Comment by shyim** [comment]
Yes it is unrelated

**Comment by smurfy** [comment]
Ok, cool any chance to get it tagged? to use non git url in my composer to install :)

**Comment by shyim** [comment]
sure I tagged it :) https://github.com/shyim/testcontainer/releases/tag/0.1.1

thank you again! :)

**Pull request merged**
